apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/          # This manages the controllers
  - infrastructure/       # This manages your Postgres and StorageClass
  - deployment.yaml       # This manages your Python app

